# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MovieBrowser' do
	pod 'ObjectMapper', '~> 1.1.5'
	pod 'Alamofire', '~> 3.2.1'
	pod "PKHUD"
	pod "PromiseKit"
	pod "SDWebImage"
end